### PR TITLE
ethereum: disallow http(s) RPC transports

### LINKED ISSUE #776: Ethereum adapter needs better nonce management
## Context
Ethereum transactions are required to contain a nonce. The nonce of a transaction is zero-based, and must be equal to the number of transactions previously submitted (and accepted into the mempool) by the account signing the transaction. If a transaction is submitted with an incorrect nonce, it is rejected before entering the mempool. This includes cases when transactions are submitted in rapid succession, but out of order.

## Expected Behavior
- Caliper will submit transactions in the correct order without nonce errors.
- Other transaction errors will not trigger nonce errors.

## Actual Behavior
- Caliper sometimes submits transactions out of order. When this happens, all outstanding transactions fail due to incorrect nonces.
- When transaction submission errors occur that cause the transaction to not enter the mempool, all following transactions for a given account fail.

## Possible Fix

There are actually three issues here.

1. Somehow async requests being made to the node's RPC interface are being reordered, causing them to arrive out of order.
2. The ethereum adapter does not detect transaction submission failures and update the state of its internal nonce tracking accordingly.
3. Many transactions are generated at once for the same account, meaning that even if nonce tracking were updated accordingly on transaction submission failures, many in-flight transactions will fail.

## Steps to Reproduce
1. Run a benchmark with a large transaction count against an ethereum client - it's most noticeable when running against ganache-cli, but it also occurs when benchmarking Besu.

## Context
This bug is impacting users' ability to benchmark Besu and other compatible ethereum client implementations. 

## Your Environment

* Version used: v0.3.0 and current master
* Environment name and version (e.g. Chrome 39, node.js 5.4): various nodejs versions from v8.17.0 to v11.19.0.
* Operating System and version (desktop or mobile): Ubuntu 19.10

### PR DESCRIPTION
**Pull request by benjamincburns**
Fixes #776. See https://github.com/hyperledger/caliper/issues/776#issuecomment-624771622 for more info.

Signed-off-by: Ben Burns <803016+benjamincburns@users.noreply.github.com>

### CODE REVIEW

**Comment by benjamincburns** [comment]
The CI errors appear to be caused by something to do with the prometheus observer.

Unless there's some code in those tests that uses the ethereum adapter via an HTTP provider, it's impossible that this change could have caused this error. I'll double check for usages of `caliper-ethereum` in the failing tests just to be sure.

**Comment by benjamincburns** [comment]
My apologies - I missed the linter errors - should be fixed up now.

**Comment by nklincoln** [comment]
There's a connection error showing at the moment - is this a port mismatch? The config files (docker compose) used in the integration test are exposing/mapping a single port (8545) rather than a port range as done in besu, and there has been a change in the network config files to be 8546

(https://github.com/hyperledger/caliper/blob/9b571dd2f48ef745ff929c1cb1daebeaa998dae7/packages/caliper-tests-integration/ethereum_tests/config/docker-compose.yml#L26)

**Comment by benjamincburns** [comment]
> There's a connection error showing at the moment - is this a port mismatch? The config files (docker compose) used in the integration test are exposing/mapping a single port (8545) rather than a port range as done in besu, and there has been a change in the network config files to be 8546
> 
> (
> 
> https://github.com/hyperledger/caliper/blob/9b571dd2f48ef745ff929c1cb1daebeaa998dae7/packages/caliper-tests-integration/ethereum_tests/config/docker-compose.yml#L26
> 
> )

Good catch - I forgot to change the exposed port.

**Pull request merged**
