### PR TITLE
Doc changes related to value parameter for payable functions in Ethereum.

### PR DESCRIPTION
**Pull request by nachikettapas**
Doc changes related to value parameter for payable functions in Ethereum. Document changes related to PR #1122.

### CODE REVIEW

**Comment by nklincoln** [comment]
@nachikettapas - thanks for this, the changes need to go into the vNext section though ... once an "official release" is cut, the changes in vNext are moved into a release section as required (ie a minor or major version bump) that is accessible from the side drop down.

**Comment by nachikettapas** [comment]
> @nachikettapas - thanks for this, the changes need to go into the vNext section though ... once an "official release" is cut, the changes in vNext are moved into a release section as required (ie a minor or major version bump) that is accessible from the side drop down.

@nklincoln thank you for your comment and review. I pushed the changes to vNext.

**Comment by nklincoln** [comment]
Hi @nachikettapas - thanks for the update, only requirement now is to remove the addition to the 0.4.2 docs. The feature will only be available in 0.4.3-unstable (current vNext target) once merged and auto-published.

I suspect you will want to get direct access to the built packages, they will be the unstable item in https://www.npmjs.com/package/@hyperledger/caliper-cli (check out the versions tab)

**Comment by nachikettapas** [comment]
> Hi @nachikettapas - thanks for the update, only requirement now is to remove the addition to the 0.4.2 docs. The feature will only be available in 0.4.3-unstable (current vNext target) once merged and auto-published.

@nklincoln  - I understand. I will try to revert the changes to 0.4.2 docs and push the changes.

> I suspect you will want to get direct access to the built packages, they will be the unstable item in https://www.npmjs.com/package/@hyperledger/caliper-cli (check out the versions tab)

I am not sure if I understand this. Sorry for the naivety, but can you please elaborate this comment?

**Comment by nklincoln** [comment]
@nachikettapas - sure ..  Every time a PR is merged, we publish the code under an "unstable" tag so that it is immediately available for those wishing to use the latest (unsupported) version of Caliper, with all features present in the master branch code. The unstable version is referred to as "vNext" in the docs. 

Once your feature is merged, it will only be usable in the unstable versions until the next official Caliper version is released

**Comment by nachikettapas** [comment]
> @nachikettapas - sure .. Every time a PR is merged, we publish the code under an "unstable" tag so that it is immediately available for those wishing to use the latest (unsupported) version of Caliper, with all features present in the master branch code. The unstable version is referred to as "vNext" in the docs.
> 
> Once your feature is merged, it will only be usable in the unstable versions until the next official Caliper version is released

Thank you for your patience.

**Review by nklincoln — APPROVED** [review]
👍

**Comment by nklincoln** [comment]
Thanks for the contribution :D

**Pull request merged**
