### PR TITLE
Delete logo image stored in repo since it fetches from an external link

### PR DESCRIPTION
**Pull request by PrathamSikka24**
**Title:** Add Missing Hyperledger Fabric Logo

## Checklist
 - [x] A link to the issue/user story that the pull request relates to
 - [x] How to recreate the problem without the fix
 - [x] Design of the fix
 - [x] How to prove that the fix works
 - [ ] Automated tests that prove the fix keeps on working
 - [x] Documentation - any JSDoc, website, or Stackoverflow answers?

## Issue/User story
This pull request addresses the issue where the Hyperledger Fabric logo was not displayed on the landing page, as described in issue #1531 .

## Steps to Reproduce
1. Navigate to the Hyperledger Caliper landing page.
2. Scroll down to the "Supported Blockchains" section.
3. Notice the absence of the Hyperledger Fabric logo, with only the alt text visible.

## Existing issues
- [x] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
Related issue: [link to the GitHub issue you created](https://github.com/hyperledger/caliper/issues/1531)

## Design of the fix
The fix involved adding the missing logo image to the assets directory and updating the HTML source to point to the correct image file location. The previous image no longer existed.

## Validation of the fix
The fix was validated locally by refreshing the landing page and confirming that the Hyperledger Fabric logo is now displayed correctly.

## Automated Tests
No automated tests were added as this fix is related to the static content of the website.

## What documentation has been provided for this pull request
The change is self-documenting; the addition of the image file is the only update required.

### CODE REVIEW

**Comment by davidkel** [comment]
@PrathamSikka24 many thanks for the PR, unfortunately the commit isn't signed so we can't do anything with it. Please could you sign the commit and repush ?

**Comment by PrathamSikka24** [comment]
@davidkel Thank you for bringing that to my notice. I've signed and re-pushed the commit. Please review it and let me know if anything else needs to be done.

**Review by davidkel — CHANGES_REQUESTED** [review]
Rather than storing the image in our repo, we could just reference the one stored in the hyperledger fabric github repo which is
https://raw.githubusercontent.com/hyperledger/fabric/main/docs/source/images/hyperledger_fabric_logo_color.png

Hopefully then we would also pick up the logo change when it occurs.

**Comment by PrathamSikka24** [comment]
We can reference the logo directly from the Hyperledger Fabric repo. However, the image in the link has a grey background, unlike our other UI images(logos of Hyperledger Besu, Ethereum), which are transparent. Could we find a transparent version or adapt this one?

For now, I have committed the change as you've suggested. Please let me know in case of anything else.

**Comment by PrathamSikka24** [comment]
We can reference the logo directly from the Hyperledger Fabric repo. However, the image in the link has a grey background, unlike our other UI images(logos of Hyperledger Besu, Ethereum), which are transparent. Could we find a transparent version or adapt this one?

I have incorporated the necessary suggestion for the image link. I apologize for mistakenly making an extra PR; please don't mind that. Do tell me if anything else needs to be done.

**Review by davidkel — APPROVED** [review]
LGTM, many thanks for the contribution

**Pull request merged**
