### PR TITLE
add caliper FAQ

### PR DESCRIPTION
**Pull request by houqinghui**
add caliper FAQ.

### CODE REVIEW

**Comment by nklincoln** [comment]
Quite a few of the items here should probably point to the relevant section of the docs ... and if those sections of the docs are not clear enough then they should be modified/enhanced.

My suggestion would be that everything above (but not including) "How to test the blockchain system that caliper does not support currently" link to existing documentation, and everything else remain unchanged

**Comment by houqinghui** [comment]
> Quite a few of the items here should probably point to the relevant section of the docs ... and if those sections of the docs are not clear enough then they should be modified/enhanced.
> 
> My suggestion would be that everything above (but not including) "How to test the blockchain system that caliper does not support currently" link to existing documentation, and everything else remain unchanged

what do you mean the existing documentation is ? should i  make a new documentation for that question?

**Comment by houqinghui** [comment]
@nklincoln @aklenik  i have revise the FAQ documentation, please review it.

**Comment by houqinghui** [comment]
@panyu4 @aklenik  I update the FAQ documentation, please review it again.

**Pull request merged**
