### PR TITLE
Removed tape-related code

### PR DESCRIPTION
**Pull request by aklenik**
Signed-off-by: Attila Klenik <a.klenik@gmail.com>

## Issue/User story
Resolves Issue #193

### CODE REVIEW

**Comment by aklenik** [comment]
@panyu4 Could you review it, please?

**Comment by panyu4** [comment]
> @panyu4 Could you review it, please?



> @panyu4 Could you review it, please?

I'll review it wright now.

**Comment by panyu4** [comment]
@aklenik , LGTM.  
There is one suggestion:  when using tape in the original code , the user will get a summary information such like "9 tests, 9 pass, 0 fail " at the end of the test.  But now, without tape, the user has to go through all of the information to see if all the tests are successfully finished. I think this information should be added into the framework  as a tips which indicates if the tests were going well.

**Comment by aklenik** [comment]
@panyu4 Added the final test report. I count the executed rounds only. 

There were some fail counts for adapter errors previously, but those shouldn't be counted, in my opinion. The numbers should correspond to the rounds defined in the config, and that's the philosophy I followed now.

**Comment by panyu4** [comment]
@aklenik I agree.

**Pull request merged**
