### PR TITLE
Adding changes related to value parameter for payable function in Ethereum.

### PR DESCRIPTION
**Pull request by nachikettapas**
Currently it is not possible to pass value parameter to payable functions in Ethereum. An issue has been raised in #1106. A corresponding issue has been raised in caliper-benchmark repo #81.

### CODE REVIEW

**Comment by nklincoln** [comment]
@nachikettapas - thank you for your contribution 👍 

With the new feature, would you be able to extend one of the integration tests to incorporate use of the change?

It would be nice to have the feature documented (looks like the docs change would be very small), and this would be with a small edit in the gh-pages branch. There is a short readme that explains how to make the changes, and we'd certainly be happy to help if you reach out to us on rocket chat

**Comment by nachikettapas** [comment]
Hey @nklincoln. Thank you for your comment. 

1. What do you mean by extending the integration tests? I have made changes to the integration tests related to Ethereum in caliper-tests-integration. I made changes so that the initial opening of the account is funded with the initial balance (makes logical sense). Are there any other tests that need to be modified? Are you referring to caliper-benchmark examples?

2. I will make the changes to gh-pages with the details of the feature.

**Comment by nklincoln** [comment]
Hi @nachikettapas

I had a dig in the output logs and have spotted `Error: Can not send value to non-payable contract method or constructor` so there might be some additional changes required to the test contract being used as well? 

In reality I think this highlights a failing in the integration tests, since we only fail on catastrophic error and not a transaction failure (which is default caliper behaviour)

Are you able to access the output from the azure build?

**Comment by nachikettapas** [comment]
> Hi @nachikettapas
> 
> I had a dig in the output logs and have spotted `Error: Can not send value to non-payable contract method or constructor` so there might be some additional changes required to the test contract being used as well?
> 
> In reality I think this highlights a failing in the integration tests, since we only fail on catastrophic error and not a transaction failure (which is default caliper behaviour)
> 
> Are you able to access the output from the azure build?

I am sorry I forgot to modify the example contract. I made the changes and pushed them.
How do I access the output of the azure build?

**Comment by nachikettapas** [comment]
> > Hi @nachikettapas
> > I had a dig in the output logs and have spotted `Error: Can not send value to non-payable contract method or constructor` so there might be some additional changes required to the test contract being used as well?
> > In reality I think this highlights a failing in the integration tests, since we only fail on catastrophic error and not a transaction failure (which is default caliper behaviour)
> > Are you able to access the output from the azure build?
> 
> I am sorry I forgot to modify the example contract. I made the changes and pushed them.
> How do I access the output of the azure build?

**Comment by nklincoln** [comment]
@nachikettapas 

Thanks for the update - once the companion docs are ready I will approve/merge both at the same time 👍

**Comment by nachikettapas** [comment]
> @nachikettapas
> 
> Thanks for the update - once the companion docs are ready I will approve/merge both at the same time 👍

@nklincoln  Thank you very much for the review. I created a PR #1124 for the changes related to documentation.

**Review by nklincoln — APPROVED** [review]
LGTM 👍

**Comment by nklincoln** [comment]
@nachikettapas - thanks for the contribution 👍

**Pull request merged**
