### PR TITLE
Typo fix in fix-load documentation 

### PR DESCRIPTION
**Pull request by duckling69**
Fix [1471](https://github.com/hyperledger/caliper/issues/1471)  
## Checklist
 - [x] A link to the issue/user story that the pull request relates to

## Existing issues
- [x] [GitHub Issues](https://github.com/hyperledger/caliper/issues)

#1471

### CODE REVIEW

**Comment by duckling69** [comment]
can you review this? // @aklenik  @davidkel

**Review by aklenik — DISMISSED** [review]
The issue was only about the fix-load rate controller. Changing the linear-rate (and possibly other) docs is incorrect, since the code indeed uses the `startingTps` naming.

**Review by davidkel — CHANGES_REQUESTED** [review]
You missed changing the description of the options, it still says `startingTps`
```
### Options and use
The fixed-load controller can be specified by setting the rate controller `type` to the `fixed-load` string.
Controller options include:
- `startingTps`: the initial rate at which transactions are cumulatively sent to the SUT by all workers
- `transactionLoad`: the number of transactions being processed by the SUT that is to be maintained
The fixed load controller, aiming to maintain a SUT transaction load of 5, with a starting TPS of 100, is specified through the following controller option:
```json
{
  "type": "fixed-load",
  "opts": {
    "transactionLoad": 5,
    "startTps": 100
  }
}
```

**Comment by duckling69** [comment]
Thanks for reviewing I think I've done all reviewed changes // @davidkel @aklenik

**Review by davidkel — APPROVED** [review]
LGTM, many thanks for the contribution

**Comment by davidkel** [comment]
@aklenik Looks like I am blocked from merging, I guess you need to approve

**Pull request merged**
