### PR TITLE
Use common utility for path resolution

### PR DESCRIPTION
**Pull request by aklenik**
Related to Issue #95, this PR unifies the path resolution of different modules, by using [the following](https://github.com/hyperledger/caliper/blob/6cf2891736c60dfd5c0a3221f36b1841dc79318d/src/comm/util.js#L51) utility function.

Now every path in the config files can be set either as a relative path to the Caliper root directory or as an absolute path.

@nklincoln I successfully run a Composer sample benchmark, but could you review the Composer-related part just in case?
@haojun Can you tag someone from the Iroha contributors to review the Iroha-related part? Although those were (I hope) straightforward modifications.

Signed-off-by: Attila Klenik <a.klenik@gmail.com>

### CODE REVIEW

**Comment by haojun** [comment]
@stinger112 can help to review the iroha part

**Comment by nklincoln** [comment]
works with Composer 🥇

**Comment by haojun** [comment]
@stinger112 , would you please review it?

**Comment by haojun** [comment]
@stinger112 I've tested it with iroha, it works according to my test. So i'd like to approve this pr first. If you find any problem later, you can open an issue on it.

**Pull request merged**
