### PR TITLE
Modify docker rm error

### PR DESCRIPTION
**Pull request by Arucald**
Try to resolve docker rm error
#352 

I am a fresh man on github who use the Github Client to pull request , so it doesn't show the sign-off procedure. 

However , the PR has been submitted successfully.

### CODE REVIEW

**Comment by aklenik** [comment]
@Arucald Good catch! The sign-off is needed for the commit, merging is automatically blocked until then. You can amend your commit from the command line with a sign-off.

And while we're talking about amending the commit, this bug is probably also present in every other network configuration file. Any chance you could also fix those? :)

**Comment by houqinghui** [comment]
> @Arucald Good catch! The sign-off is needed for the commit, merging is automatically blocked until then. You can amend your commit from the command line with a sign-off.
> 
> And while we're talking about amending the commit, this bug is probably also present in every other network configuration file. Any chance you could also fix those? :)

Those bugs have been fixed. you can reveiw it.

**Comment by panyu4** [comment]
@Arucald , sorry for late review. Since we got a large change in Caliper, this PR needs to rebase and resolve some conflicts.

**Comment by panyu4** [comment]
Since there are some conflicts and errors in this PR , it will be closed and the pr  #446 will resolve this issue.

**Pull request closed without merging**
