### PR TITLE
extract main.js

### PR DESCRIPTION
**Pull request by Hatuw**
Extract the `main.js` in different benchmarks.

### CODE REVIEW

**Comment by haojun** [comment]
@Hatuw 
Thanks for your contribution.
We are now considering changing the directory structure for benchmarks, moving main.js outside is an option and we'd like to consider it together later.

**Comment by Hatuw** [comment]
yet..how to contribute to this project? It seems that it is unable to pass the checks. Tks~

**Comment by haojun** [comment]
You should using 'git commit -s' to sign off your commit.

**Comment by panyu4** [comment]
Since there's no activity there I'm closing this PR.

**Pull request closed without merging**
