### PR TITLE
Refactor Caliper for publishing to npm

### PR DESCRIPTION
**Pull request by nklincoln**
This is a significant change to the Caliper project to enable isolated publishing of the following packages to npm at differing levels:
- caliper-core
- caliper-adapters (fabric, sawtooth, iroha ...)
- caliper-cli

The project has been restructured to isolate each adapter in its own package, retain common caliper code in a single package, and to enable the creation of a "calliper-application" that has a one-way dependancy on the core/adaptor packages. In addition to file relocation, some files have been renamed to assist clarity and retain convention.

The code flow is now to pass `caliper-flow.js` (previously bench-flow.js) configuration files, a client factory and a workspace location. The client factory is used to spawn clients of a specific type, and the workspace path is used to enable path resolution to required configuration files etc.

`caliper-application` exists as an example application that drives a benchmark. We can and should break it into a published `cli` module that can be passed user configuration matching the required structure(s), however ... for this we should probably enable such things through yoeman generators (creation of required folder structure etc) ... and so it is out of the scope for this change. It contains two script files:
- `run-benchmark.js` (... runs a target benchmark)
- `start-zoo-client.js` (.. stands up a zoo client with a client factory)

Lerna, a javascript package management tool has been introduced to facilitate easier package management - it is capable of bootstrapping the project and managing any cross dependancies between packages.

The Travis build has been modified to:
- run the caliper-application `run-benchamrk.js` script targeting composer, fabric, fabric-ccp targets.
- fail when a benchmark fails (🥇 )
- pass when the benchmark passes (👍 )

There are *many* file changes here, though the majority are config files due to the refactoring. To run the new code, refer to the README.md file in `caliper/packages/caliper-application/README.md` ... and follow the code from the `scripts/run-benchmark.js` file.

Signed-off-by: nkl199@yahoo.co.uk <nkl199@yahoo.co.uk>

### CODE REVIEW

**Comment by feihujiang** [comment]
Looks good to me, a greate change :+1: .  Just a few minor points as the following,  
1. when running 'npm run bootstrap', it takes too much time and no output information, so users don't know what's going on or whether the command fail or not. 
2. The paths of some chaincodes are wrong in network config file.  
3.Couldn't run Benchmark with Distributed Clients on different hosts. the reason is that the path of the config file is the absolute path, not the relative path.
4.There are some pattern errors when running 'npm run lint', and has the path errors in .eslintignore file.

**Comment by feihujiang** [comment]
And could we use the following information in the network config file to remove -t blockchain target type option?
caliper:
  **blockchain: fabric-ccp**

**Comment by panyu4** [comment]
@nklincoln , good job.  Here is one problem when trying to run a benchmark. When running with the command `npm run bootstrap` , Caliper is always not able to installed successfully. If it failed, the file `package.json` actually was changed. So if the user would like to install it again, he/she needs to stash changes first using `git stash`, then run with the commands `npm run repoclean` and `npm run bootstrap`.   As @feihujiang said, some tips should be provided when running bootstrap and the file `package.json` should be able to go back to the original version if current installation fails.  I think this modification can be made by another PR.

**Comment by feihujiang** [comment]
Since this PR is really a large change and the above minor issues can be resolved by submitting new PRs, I will  merge this PR first and submit some minor modifications later.

**Comment by siatzhuliang** [comment]
HI，When I use npm run bootstrap, I always report an error and cannot run. What is the reason?Thanks
`> caliper@0.1.0 bootstrap /home/zhuliang/performance-caliper/caliper
> lerna bootstrap

lerna info version 2.0.0
lerna info Bootstrapping 8 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm WARN deprecated grpc-web-client@0.7.0: This package has been deprecated in favor of @improbable-eng/grpc-web
lerna ERR! execute npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
lerna ERR! execute npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
lerna ERR! execute npm WARN deprecated text-encoding@0.6.4: no longer maintained
lerna ERR! execute npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
lerna ERR! execute npm WARN deprecated core-js@2.3.0: core-js@<2.6.6 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
lerna ERR! execute npm WARN deprecated hawk@6.0.2: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.
lerna ERR! execute npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
lerna ERR! execute npm ERR! code 1
lerna ERR! execute npm ERR! Command failed: /usr/bin/git clone -q git://github.com/debris/bignumber.js.git /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501
lerna ERR! execute npm ERR! /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501/.git: 权限不够
lerna ERR! execute npm ERR!
lerna ERR! execute
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     /home/zhuliang/.npm/_logs/2019-05-21T02_09_33_869Z-debug.log
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (/home/zhuliang/performance-caliper/caliper/node_modules/execa/index.js:210:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm install
lerna ERR! execute npm WARN deprecated grpc-web-client@0.7.0: This package has been deprecated in favor of @improbable-eng/grpc-web
lerna ERR! execute npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
lerna ERR! execute npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
lerna ERR! execute npm WARN deprecated text-encoding@0.6.4: no longer maintained
lerna ERR! execute npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
lerna ERR! execute npm WARN deprecated core-js@2.3.0: core-js@<2.6.6 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
lerna ERR! execute npm WARN deprecated hawk@6.0.2: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.
lerna ERR! execute npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
lerna ERR! execute npm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
lerna ERR! execute npm ERR! code 1
lerna ERR! execute npm ERR! Command failed: /usr/bin/git clone -q git://github.com/debris/bignumber.js.git /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501
lerna ERR! execute npm ERR! /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501/.git: 权限不够
lerna ERR! execute npm ERR!
lerna ERR! execute
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     /home/zhuliang/.npm/_logs/2019-05-21T02_09_33_869Z-debug.log
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (/home/zhuliang/performance-caliper/caliper/node_modules/execa/index.js:210:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute   stack: 'Error: Command failed: npm install\nnpm WARN deprecated grpc-web-client@0.7.0: This package has been deprecated in favor of @improbable-eng/grpc-web\nnpm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead\nnpm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam\nnpm WARN deprecated text-encoding@0.6.4: no longer maintained\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\nnpm WARN deprecated core-js@2.3.0: core-js@<2.6.6 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.\nnpm WARN deprecated hawk@6.0.2: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.\nnpm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm ERR! code 1\nnpm ERR! Command failed: /usr/bin/git clone -q git://github.com/debris/bignumber.js.git /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501\nnpm ERR! /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501/.git: 权限不够\nnpm ERR! \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/zhuliang/.npm/_logs/2019-05-21T02_09_33_869Z-debug.log\n\n    at Promise.all.then.arr (/home/zhuliang/performance-caliper/caliper/node_modules/execa/index.js:210:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: 'npm WARN deprecated grpc-web-client@0.7.0: This package has been deprecated in favor of @improbable-eng/grpc-web\nnpm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead\nnpm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam\nnpm WARN deprecated text-encoding@0.6.4: no longer maintained\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\nnpm WARN deprecated core-js@2.3.0: core-js@<2.6.6 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.\nnpm WARN deprecated hawk@6.0.2: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.\nnpm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm ERR! code 1\nnpm ERR! Command failed: /usr/bin/git clone -q git://github.com/debris/bignumber.js.git /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501\nnpm ERR! /home/zhuliang/.npm/_cacache/tmp/git-clone-4e247501/.git: 权限不够\nnpm ERR! \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/zhuliang/.npm/_logs/2019-05-21T02_09_33_869Z-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm install',
lerna ERR! execute   timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caliper@0.1.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the caliper@0.1.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zhuliang/.npm/_logs/2019-05-21T02_09_34_112Z-debug.log`

**Comment by nklincoln** [comment]
@siatzhuliang - could you please raise a separate GitHub issue and include the node version that you are using as well as any details if you have extended any of the packages locally

Thanks
Nick

**Comment by siatzhuliang** [comment]
> @siatzhuliang - could you please raise a separate GitHub issue and include the node version that you are using as well as any details if you have extended any of the packages locally
> 
> Thanks
> Nick

No problem, in fact, I have raised this question separately, I look forward to your answer, thank you!

**Pull request merged**
